### ISSUE TITLE
Display user creating the data set

### ISSUE THREAD

**Issue by m6121** [SFB-ELAINE/ckanext-elaine_theme#1]
Though additional information such as the author and maintainer of the dataset are displayed if defined in the meta data, the actual user uploading the data is not displayed in the web interface.
This should be included as further information.

**Comment by hayley-leblanc** [comment]
Added with commit https://github.com/SFB-ELAINE/ckanext-elaine_theme/commit/04a78559ce9473f70b65ec437180fc0bdcf4910a.
